apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports: 
  - port: 80
    name: web
  clusterIP: None
  selector: 
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector: #设置标签选择器
    matchLabels: #设置标签选择器匹配的pod拥有的标签
      app: nginx #具体的标签与标签值

  template: 
    metadata: #pod 设置标签
      labels: # 标签值的设定
        app: nginx # 标签值的key与值
    spec: #pod 的期望状态
      containers:  # 容器的设置
      - name: nginx # 容器的名字
        image: nginx # 运行容器的镜像
        ports: # 端口的设置
        - containerPort: 80 # 容器暴漏的端口
          name: web # 端口名字的设置
        volumeMounts: # 挂载存储设定
        - name: www # 存储的名字
          mountPath: /usr/share/nginx/html # 挂载的目录
  volumeClaimTemplates: # 存储属性设置
  - metadata: # 存储元数据
       name: www # 物理存储的名字
    spec: #期望实际运行状态配置
      accessModes: # 访问模式
      - ReadWriteOnce
      resources: # 空间大小设置
        requests:
          storage: 5Gi  
