kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None #None 无头服务，不对集群外部使用--尘曦
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
