apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  ports:
  - name: web
    port: 80
  clusterIP: None
  selector: #service 定义绑定拥有一下标签的pod
    app: storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec: 
  selector: #service 定义绑定拥有一下标签的pod
    matchLabels:
      app: storage
  serviceName: "storage" #指定service名字
  replicas: 2
  template: # pod属性定义
    metadata: 
      labels: #打标签
        app: storage
    spec: #pod期望运行状态定义
      containers: # 容器运行状态定义
      - name: web # 容器名字
        image: nginx # 运行的镜像
        imagePullPolicy: IfNotPresent # 镜像获取策略
        ports: #暴漏端口设置
        - name: web
          containerPort: 80 #容器暴漏端口
          protocol: TCP # 端口协议；默认TCP
        volumeMounts:
        - name: www #这个文件里指的动态申请的名字，也可指定现有的pvc
          mountPath: /usr/share/nginx/html #挂载的指定目录        
  volumeClaimTemplates: # 存储申请模板
  - metadata:
      name: www #动态申请的名字
      annotations: 
        volume.beat.kubernetes.io/storage-class: "managed-nfs-storage" #注解建议与动态存储类名字一致· 
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

