kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: fuseim.pri/ifs #这里指定存储供应者来源名称
reclaimPolicy: Delete  #指定回收策略，在这里选择的是Delete，与PV相连的后端存储完成Volume的删除操作
volumeBindingMode: Immediate #指定绑定模式，在这里选择的是即刻绑定，也就是存储卷声明创建之后，立刻动态创建存储卷饼将其绑定到存储卷声明，另外还有"WaitForFirstConsumer",直到存储卷声明第一次被容器组使用时，才创建存储卷，并将其绑定到存储卷声明
